modLoader="javafml"
loaderVersion="${loader_version_range}"
license="AGPL-3.0"
issueTrackerURL="https://github.com/Bismuth-Software/Bon-Appetit/issues"

[[mods]]
modId="sourcecubed"
version="0.2.0-21.1"
displayName="source³"

displayURL="https://modrinth.com/mod/sourcecubed/"
logoFile="sourcesquared.png"
authors="Ashley"
credits="Lein"
description='''Source, but Cubed'''

[[mixins]]
config="sourcecubed.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json
[[dependencies.bonappetit]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.bonappetit]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[features.bonappetit]
openGLVersion="[3.2,)"
